### ISSUE TITLE
Model does not work

### ISSUE THREAD

**Issue by zhouzyhfut** [kykiefer/depression-detect#9]
Hi, sorry for bothering you. I'm trying to reproduce the experimental results about your work. However, the predictions of the model are all the same:

- y_train_pred=[0,...,0];
- y_train_pred_proba: [[0.50005114 0.4999489 ] .

It seems that the model doesn't learn anything. Can you help me solve this problem? Thank you.

**Comment by omarmetwally55** [comment]
where did you stop in the code ?

**Comment by wuqing778** [comment]
嗨，很抱歉打扰您了。我正在尝试重现有关您的作品的实验结果。但是在random_sampling处出现了错误
Traceback (most recent call last):
  File "E:/学习/progress-pycharm/CNN+频谱图  抑郁识别-奇基弗/特征/random_sampling.py", line 240, in <module>
    create_sample_dicts(crop_width=125)
  File "E:/学习/progress-pycharm/CNN+频谱图  抑郁识别-奇基弗/特征/random_sampling.py", line 127, in create_sample_dicts
    crop_width=crop_width)
  File "E:/学习/progress-pycharm/CNN+频谱图  抑郁识别-奇基弗/特征/random_sampling.py", line 52, in determine_num_crops
    shortest_clip = min(merged_dict.items(), key=lambda x: x[1].shape[1])
ValueError: min() arg is an empty sequence
请问怎么解决呀，环境用的python3.5

**Comment by wuqing778** [comment]
> Hi, sorry for bothering you. I'm trying to reproduce the experimental results about your work. However, the predictions of the model are all the same:
> 
> * y_train_pred=[0,...,0];
> * y_train_pred_proba: [[0.50005114 0.4999489 ] .
> 
> It seems that the model doesn't learn anything. Can you help me solve this problem? Thank you.

Have you solved your problem now? I have the same problem as you
